version: "3.8"
services:
  mongodb:
    image:  'mongo' 
    container_name: mongodb
    volumes:
      - data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: jin
    #  MONGO_INITDB_ROOT_PASSWORD: helloworld
    #  #- MONGO_INITDB_ROOT_USERNAME=jin
    env_file:
      - ./env/mongo.env

    # not necessary
    #networks:
    # - goals-net
  backend:
    build: ./backend
    container_name: backend
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    #    some-arg: 1
    ports:
      - '80:80' #host:container
    volumes:
      - logs:/app/logs
      - ./backend:/app #bind mount
      - /app/node_modules
    env_file:
      ./env/backend.env
    depends_on: # dependency
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src

    # -it flag
    stdin_open: true
    tty: true

    depends_on:
      - backend

# volume keys
volumes:
  data:
  logs:
