version: "3.8"
services:
  mongodb:
    image:  'mongo' 
    volumes:
      - data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: jin
    #  MONGO_INITDB_ROOT_PASSWORD: helloworld
    #  #- MONGO_INITDB_ROOT_USERNAME=jin
    env_file:
      - ./env/mongo.env

    # not necessary
    #networks:
    # - goals-net
  #backend:
  #frontend:

volumes:
  data:
